# Generated by Django 3.2.5 on 2021-08-30 14:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tasks list name', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Task unique ID', primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(help_text='Input task name here', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Task description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attachments', models.FileField(blank=True, upload_to='tasks/attachments/%Y/%m/%d/')),
                ('status', models.CharField(choices=[('Do', 'Done'), ('Ip', 'In progress'), ('Ns', 'Not started')], default='Ns', max_length=2)),
            ],
        ),
    ]
