# Generated by Django 3.2.5 on 2021-08-27 20:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='List of tasks', max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('created_at', models.DateTimeField(auto_created=True)),
                ('id', models.UUIDField(default=uuid.UUID('ec854247-6ded-4da5-a2ab-a219954692ac'), help_text='Unique ID for each task', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Enter task name', max_length=50)),
                ('description', models.CharField(blank=True, help_text='Enter task description', max_length=250)),
                ('status', models.BooleanField(help_text='task complete status')),
                ('list', models.ManyToManyField(help_text='All lists where this task would be displayed', to='todo.List')),
            ],
        ),
    ]
