# Generated by Django 3.2.5 on 2021-08-28 11:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='name',
            field=models.CharField(help_text='List of tasks', max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.UUIDField(default=uuid.UUID('72ef830d-40e5-4439-bb82-09df168c163a'), help_text='Unique ID for each task', primary_key=True, serialize=False),
        ),
    ]
