# Generated by Django 3.2.5 on 2021-08-30 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='in_lists',
            field=models.ManyToManyField(to='todo.List'),
        ),
    ]
