# Generated by Django 3.2.5 on 2021-08-28 12:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20210828_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c5c409ac-8241-4a42-ac58-11c178763631'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.UUIDField(default=uuid.UUID('5d4fe4b3-6ee7-4f90-9422-6c1a9ebcbb8e'), help_text='Unique ID for each task', primary_key=True, serialize=False),
        ),
    ]
