# Generated by Django 3.2.5 on 2021-08-28 12:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20210828_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a5978c3a-ff93-4448-a49a-38e6e3eaf0c4'), help_text='Unique ID for each task', primary_key=True, serialize=False),
        ),
    ]
